name: Run tests

on: [push, pull_request]

jobs:
  windows-build-only:
    name: Java ${{ matrix.java-version }} Maven Build on windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: ["8", "11", "21" ]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          cache: 'maven'
          java-version: ${{ matrix.java-version }}

      - name: Build with Maven
        run: |
          mvn -B clean package -DskipTests

  macos-test:
    name: Java ${{ matrix.java-version }} Maven Test on macos
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: ["11", "21" ]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          cache: 'maven'
          java-version: ${{ matrix.java-version }}

      - name: Build with Maven
        run: |
          mvn -B clean test -Dsurefire.excludes="com/aliyun/sdk/service/oss2/Client*Test.java,com/aliyun/sdk/service/oss2/vectors/Client*Test.java"

  linux-test:
    name: Java ${{ matrix.java-version }} Maven Test on ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: ["8", "11", "17", "21" ]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          cache: 'maven'
          java-version: ${{ matrix.java-version }}

      - name: Build with Maven
        run: |
          mvn -B clean test -Dsurefire.excludes="com/aliyun/sdk/service/oss2/Client*Test.java,com/aliyun/sdk/service/oss2/vectors/Client*Test.java"

  test-graalvm:
    name: GraalVM Maven Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image'

      - name: Build with Maven
        run: |
          mvn -B clean test -Dsurefire.excludes="com/aliyun/sdk/service/oss2/Client*Test.java,com/aliyun/sdk/service/oss2/vectors/Client*Test.java"
